# Generated by Django 4.2.5 on 2023-09-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lego", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legoset",
            old_name="parts",
            new_name="parts_old",
        ),
        migrations.CreateModel(
            name="PartInSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lego.legopart"
                    ),
                ),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lego.legoset"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="legoset",
            name="parts_old",
        ),
        migrations.AddField(
            model_name="legoset",
            name="parts",
            field=models.ManyToManyField(
                related_name="sets", through="lego.PartInSet", to="lego.legopart"
            ),
        ),
    ]
