# Generated by Django 5.1.3 on 2024-11-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lego", "0003_shape_legopart_shape"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="legopart",
            name="color",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="lego.color"
            ),
        ),
    ]
