# Generated by Django 5.1.3 on 2024-11-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lego", "0004_color_legopart_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="legopart",
            name="image_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="legoset",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
