# Generated by Django 4.2.5 on 2023-09-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lego", "0004_color_legopart_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="legopart",
            name="image_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="legoset",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
