# Generated by Django 5.1.3 on 2024-12-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lego", "0005_image_url"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="legopart",
            constraint=models.UniqueConstraint(
                fields=("shape", "color"), name="unique_shape_color"
            ),
        ),
    ]
