# Generated by Django 5.1.4 on 2025-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0007_setitem_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='legopart',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legoset',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
