# Generated by Django 5.2.1 on 2025-05-22 12:55

import lego.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='num_code',
            field=models.GeneratedField(db_persist=True, expression=lego.models.NumericPrefix('lego_id'), null=True, output_field=models.CharField(max_length=30)),
        ),
    ]
