# Generated by Django 5.2.1 on 2025-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0009_shape_num_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shape',
            index=models.Index(fields=['num_code'], name='lego_shape_num_cod_707d68_idx'),
        ),
    ]
