# Generated by Django 5.2.8 on 2025-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0010_shape_num_code_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('static_path', models.CharField(max_length=150, null=True)),
                ('origin_url', models.URLField(null=True)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('static_path', 'origin_url'),
                        name='unique_static_and_origin',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('static_path__isnull', False), ('origin_url__isnull', False), _connector='OR'),
                        name='static_or_origin_not_null',
                    ),
                ],
            },
        ),
        migrations.RenameField(
            model_name='legopart',
            old_name='image',
            new_name='image_static',
        ),
        migrations.AddField(
            model_name='legopart',
            name='image',
            field=models.ForeignKey(
                null=True, on_delete=models.deletion.SET_NULL, to='lego.image'
            ),
        ),
        migrations.RenameField(
            model_name='legoset',
            old_name='image',
            new_name='image_static',
        ),
        migrations.AddField(
            model_name='legoset',
            name='image',
            field=models.ForeignKey(
                null=True, on_delete=models.deletion.SET_NULL, to='lego.image'
            ),
        ),
    ]
