# Generated by Django 6.0.1 on 2026-01-08 09:18

from django.db import migrations

POPULATE_IMAGE = """
INSERT INTO "lego_image" ("static_path", "origin_url")
(
  SELECT "lego_legopart"."image_static", "lego_legopart"."image_url"
  FROM "lego_legopart"
  WHERE ("lego_legopart"."image_url" IS NOT NULL OR "lego_legopart"."image_static" IS NOT NULL)
)
UNION
(
  SELECT "lego_legoset"."image_static", "lego_legoset"."image_url"
  FROM "lego_legoset"
  WHERE ("lego_legoset"."image_url" IS NOT NULL OR "lego_legoset"."image_static" IS NOT NULL)
);
"""

POPULATE_FOREIGN_KEYS = """
UPDATE "lego_legopart"
SET "image_id" = "lego_image"."id"
FROM "lego_image"
WHERE (
  COALESCE("lego_legopart"."image_url", 'N') = COALESCE("lego_image"."origin_url", 'N')
  AND COALESCE("lego_legopart"."image_static", 'N') = COALESCE("lego_image"."static_path", 'N')
);

UPDATE "lego_legoset"
SET "image_id" = "lego_image"."id"
FROM "lego_image"
WHERE (
  COALESCE("lego_legoset"."image_url", 'N') = COALESCE("lego_image"."origin_url", 'N')
  AND COALESCE("lego_legoset"."image_static", 'N') = COALESCE("lego_image"."static_path", 'N')
);
"""

REVERSE_POPULATE_FOREIGN_KEYS = """
UPDATE "lego_legopart"
SET "image_url" = "lego_image"."origin_url", "image_static" = "lego_image"."static_path"
FROM "lego_image"
WHERE "lego_legopart"."image_id" = "lego_image"."id";

UPDATE "lego_legoset"
SET "image_url" = "lego_image"."origin_url", "image_static" = "lego_image"."static_path"
FROM "lego_image"
WHERE "lego_legoset"."image_id" = "lego_image"."id";
"""


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0011_image_model'),
    ]

    operations = [
        migrations.RunSQL(
            sql=POPULATE_IMAGE,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=POPULATE_FOREIGN_KEYS,
            reverse_sql=REVERSE_POPULATE_FOREIGN_KEYS,
        ),
    ]
