# Generated by Django 6.0.1 on 2026-01-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0012_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legopart',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='legopart',
            name='image_static',
        ),
        migrations.RemoveField(
            model_name='legoset',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='legoset',
            name='image_static',
        ),
    ]
