# Generated by Django 6.0.6 on 2026-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0013_remove_old_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='unique_static_and_origin',
        ),
        migrations.RemoveConstraint(
            model_name='image',
            name='static_or_origin_not_null',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='static_path',
            new_name='path',
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(
                fields=('path', 'origin_url'),
                name='unique_path_and_origin',
            ),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('path__isnull', False),
                    ('origin_url__isnull', False),
                    _connector='OR',),
                name='path_or_origin_not_null',
            ),
        ),
    ]
