# Generated by Django 6.0.7 on 2026-07-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0014_remove_image_unique_static_and_origin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legopart',
            options={'ordering': ['shape']},
        ),
        migrations.AlterModelOptions(
            name='setitem',
            options={'ordering': ['part']},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'ordering': ['num_code']},
        ),
    ]
