# Generated by Django 6.1 on 2026-08-06 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0015_setitem_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legopart',
            name='color',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DB_SET_NULL,
                to='lego.color',
            ),
        ),
        migrations.AlterField(
            model_name='legopart',
            name='image',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DB_SET_NULL,
                to='lego.image',
            ),
        ),
        migrations.AlterField(
            model_name='legopart',
            name='shape',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                to='lego.shape',
            ),
        ),
        migrations.AlterField(
            model_name='legoset',
            name='image',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DB_SET_NULL,
                to='lego.image',
            ),
        ),
        migrations.AlterField(
            model_name='setitem',
            name='part',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                to='lego.legopart',
            ),
        ),
        migrations.AlterField(
            model_name='setitem',
            name='set',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                to='lego.legoset',
            ),
        ),
    ]
