from django.test import TestCase

from lego.models import Shape

from . import test_settings, get_set_info_mock, get_set_parts_mock


@test_settings
class TestGeneratedField(TestCase):
    fixtures = ["test_data"]

    def test_shape_num_code_autogenerated(self):
        self.assertEqual(Shape.objects.get(lego_id="2345pr0001").num_code, "2345")


@test_settings
class TestAddSet(TestCase):
    fixtures = ["test_data", "test_user"]

    def test_shape_num_code_autogenerated(self):
        self.client.login(username="test-user", password="test-password")
        with get_set_info_mock(), get_set_parts_mock():
            self.client.post("/lego/set/add/", data={"set_lego_id": "1122-1"})

        self.assertEqual(Shape.objects.get(lego_id="3344a").num_code, "3344")
