name: Django tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt -r test-requirements.txt

    - name: Run Tests
      env:
        DATABASE_URL: "postgresql://test_user:test_password@localhost:5432/lego"
        LEGO_SECRET_KEY: ${{ secrets.TEST_LEGO_SECRET_KEY }}
      run: |
        python manage.py collectstatic --no-input
        python manage.py check
        python manage.py test --noinput --failfast --shuffle --verbosity=2 --durations=10 --exclude-tag=browser lego
